.TH "NETSTIFF" "1" "20080327" "sbeyer" "netstiff"
.SH "NAME"
.LP
netstiff \- powerful and easy tool to check for Web and FTP updates

.SH "SYNOPSIS"
.LP
\fBnetstiff\fP [\fIoptions\fP] [\fIcommand\fP]

.SH "DESCRIPTION"
.LP
Netstiff (formerly known as webdiff) is a powerful and easy-to-use tool
which checks for Web page and/or FTP site updates. 

For the Web, updates are recognized using several test criteria
(\fCdiff\fP,
\fChtml\fP,
\fCsize\fP,
\fCdate\fP,
\fCmd5sum\fP,
\fCregexp\fP).
The FTP update checker is only able to \fCdiff\fP on directory listings and files
and to compare \fCsize\fP and \fCdate\fP of files.
Please see the configurator for more information on these methods.

Without a given command, netstiff will only check for updates 
of the specified URIs and only print those that changed, one per
line, so that the output of netstiff can easily be used by 
further scripts (e.g. \fIwget\fP or \fImail\fP).
If no configuration file exists, the configurator is launched
instead.

Netstiff exits after all configured Web pages are checked.
Occuring warnings and errors leave a message in the log file 
(\fC~/.netstiff/lastlog\fP) and on \fCstderr\fP.
Use it with \fIcron\fP if you want to check for updates regularly.

.SH "COMMANDS"
.LP
You can only pass one command to netstiff. It has to be the last argument
in the argument list.

Commands may be shortened down to one character (e.g. `c' instead of 
`configure'). Leading dashes are ignored.

If you start netstiff without command, `get' will be used.
.TP
\fBconfigure\fP
Use this command if you want to start the configurator, the interactive
configuration tool of netstiff. Of course, you may also edit the 
configuration file in \fC~/.netstiff/config\fP by hand. Using the 
configurator is recommended if you are a new netstiff user, because
it explains the possible test methods, validates your regexps, etc.
Nevertheless, the configuration file format is very easy.
See section \fBCONFIGURATION FILE\fP.
.br
The configurator will not initialize the netstiff cache for added
URIs, i.e. it will not download anything.
To do so, you have to rerun netstiff. This is a feature.
.br
If the config file does not exit, the configuration tool is started 
automatically.
.TP
\fBdiff\fP
Use this command if you want to see the differences between the last two
versions of the Web pages that are configured with test method \fCdiff\fP
or \fChtml\fP. See \fIdiff\fP\|(1). 
.TP
\fBget\fP
Use this command if you want netstiff to fetch the data from the 
specified URIs and show you only those that changed, one per line.
The behaviour is already described in \fBDESCRIPTION\fP.
.TP
\fBhelp\fP
Use this command to get usage information about netstiff. To be honest,
this manual page in conjunction with the configurator is a better 
documentation.
.TP
\fBreset\fP
Use this command after you noticed all differences with the \fBdiff\fP 
command (see above), so that \fBdiff\fP will not show you the same changes
again and again.
.TP
\fBversion\fP
This command will display version number and copyright.

.SH "OPTIONS"
.LP
You may pass the following options.
.TP
\fB--no-stderr, -S\fP
Use this option to suppress warning and error messages on \fCstderr\fP.
Thus the messages can only be seen in the log file.
.TP
\fB--workdir DIR, -W DIR\fP
Use this option if you want to specify another working directory. The
working directory is the directory where netstiff reads the configuration
file, stores the downloaded data and writes it logs.
It defaults to \fC~/.netstiff\fP.
See also section \fBBUGS\fP.

.SH "RESTRICTIONS"
.LP
There is no special case to handle status codes other than 200. In 
practice, netstiff will neither follow redirections nor will it notice
any 4xx or 5xx error code. The resulting error pages are treated as
usual Web pages. No logged message. Please check on your own.

.SH "USAGE EXAMPLE"
.LP
You want to add a new URI netstiff should check for updates.
.nf
\&        \fCnetstiff conf\fP
.fi
The configurator is not described here. I know some weaknesses in
usability, but you can get along with it.

When you are seeing your shell prompt again,
you know that netstiff should retrieve an initial 
version of the Web page you specified.
.nf
\&        \fCnetstiff\fP
.fi
After some weeks in the sun you want to see if something has changed. 
So you let netstiff check for updates.
.nf
\&        \fCnetstiff\fP
.fi
It is printing an URI! Let's see the changes!
.nf
\&        \fCnetstiff diff\fP
.fi
Oh, it is so much, that it does not fit on a screen!
.nf
\&        \fCnetstiff d | pager\fP
.fi
Now you are satisfied because you read all the changes. So you finally
do
.nf
\&        \fCnetstiff reset\fP
.fi
and netstiff forgets about the changes.

.SH "CONFIGURATION FILE"
.LP
There is no need to manually edit the configuration file
\fIWORKDIR\fC/config\fR (usually \fC~/.netstiff/config\fP),
because \fCnetstiff configure\fP should do the job.
But sometimes it is easier to edit a simple file than to
browse through menus, or you are writing another application
that changes netstiff settings.
So it is useful to describe the file format here.

.SS "RULES"
.IP " \(bu" 3
Whitespace at the begin and end of each line is ignored.
.IP " \(bu" 3
Empty lines are ignored.
.IP " \(bu" 3
A line beginning with \fC#\fP is regarded as comment.
.IP " \(bu" 3
A line beginning with \fC+\fP is regarded as option.
The \fC+\fP is followed by the \fIoption name\fR,
some whitespace and the \fIoption value\fR.
.IP " \(bu" 3
A line neither beginning with \fC#\fP nor \fC+\fP is regarded as URI.
URIs without scheme (\fChttps://\fP, \fChttp://\fP, \fCftp://\fP)
are recognized as HTTP URIs.
.IP " \(bu" 3
The configurator interprets a comment right above an URI as the title of the URI.
.IP " \(bu" 3
Options always apply to the first URI above.
Options without URI line above are \fIglobal options\fP and affect
every URI that does not override these specific options.

.SS "CONFIGURATION OPTIONS"
.LP
The following options are generally available:
.TP
\fBtest\fP
sets the test method (or test criteria).
.br
See section \fBTEST METHODS\fP for a description.
Defaults to \fCdiff\fP.
.TP
\fBtimeout\fP
sets the timeout (in seconds) for TCP connections.
.br
Defaults to 20.
.LP
The following options only affect HTTP URIs:
.TP
\fBclient\fP
set the user-agent string.
.br
Some web sites check the HTTP header field \fIUser-Agent\fP
and display different content for different agents.
By setting this field you can pretend to use Mozilla Firefox,
for example.
Because many log analyzer tools for webmasters display statistics
about that field, you may spread the word about netstiff by
setting this variable to the truth: \fCnetstiff\fP. ;-)
.br
\fIExample:\fP \fC+ client Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.12) Gecko/20080208 Galeon/2.0.4\fP
.br
This option is not set by default.
.TP
\fBlang\fP
sets the accepted languages.
.br
Internationalized web sites offer there contents in different
languages and may check the HTTP header field \fIAccept-Language\fP.
It contains a list of languages (and sometimes extra information
like associated countries) sorted by priority.
The best way to get a good value is to copy and paste it from the
preferences of your web browser.
.br
\fIExample:\fP \fCde,en;q=0.9\fP
.br
This option is not set by default.
.TP
\fBproxy\fP
sets HTTP proxy host and port.
Must be in the form \fChost:port\fP.
Will fail if no port is given.
.TP
\fBrange\fP
sets the range (in bytes) to get from a server.
.br
Use this option if you are only interested in the changes within a 
small region of a big file on a HTTP server.
Examples are \fC12000-12500\fP or \fC13000-\fP (till the end).
.br
The Range feature is not supported by all web servers or for
every content. That means, that some web servers send
the whole content instead of only the given range.
.br
This option is not set by default.
.TP
\fBreferer\fP
sets the referrer.
.br
Some web sites check the HTTP header field \fIReferer\fP
and refuse to display the wished contents if it is not appropriately set.
When clicking on a link in an ordinary web browser, 
the referrer is set to the URI, where you clicked on the link.
By setting this option to an URI, 
you can pretend clicking on a link on the web page of this URI.
Please do not use this option to `advertise' your
own homepage (so-called \fIreferer spamming\fP).
.br
This option is not set by default.
.LP
The following options only affect the test method \fChtml\fP:
.TP
\fBhtmlcmd\fP
sets the command that is used to produce non-HTML human-readable
output. The command will be run on a temporary file.
.br
Doing many experiments I got my best results using
\fC+ htmlcmd lynx -nolist -dump\fP.
Other dumpers had features, 
like justified text or well-formatted tables,
that turned out to be disadvantages 
when looking at the diffs.
.br
This option is not set by default. If you use the \fChtml\fP test
method then, a very simple mechanism will hide HTML tags.
It is possible to get good results doing that, but it is not
likely and thus not recommended to leave this option unset.
.LP
The following options only affect the test methods \fCdiff\fP and \fChtml\fP:
.TP
\fBstart\fP, \fBend\fP
\fIMotivation:\fP Many modern or CMS-generated web pages have
a dynamic and a static part. For example, at the beginning
of a web page there is always a randomly chosen citation the
author liked. At the end there is a calendar showing the current
date, a weather analysis for the next days, and some other useless
stuff.
The information you want to monitor for changes (the \fIstatic part\fP)
is situated between those dynamic parts.
It is very often possible to figure out \fItextual anchors\fP,
that indicate the start or the end of the static part.
.br
Using this options you can set regular expressions to that
anchors.
For example, if the last entry of the navigation bar is \fIImprint\fP
and thereafter comes the static part, set \fC+ start /Imprint/\fP.
I hope, you can imagine analogous examples for the \fCend\fP option.
.br
Note, that the regular expressions act on the 
unprocessed input (e.g. HTML source code),
also when using the \fChtml\fP test method.
.br
These options are not set by default.
.LP
The following options only affect FTP URIs:
.TP
\fBpassive\fP
is a boolean option (value \fCtrue\fP or \fCfalse\fP, case-insensitive).
Passive mode (PASV) will not be used on FTP connections
iff set to \fCfalse\fP.
.br
Defaults to \fCtrue\fP.

.SS "EXAMPLE"
.LP
.nf\fC
# this is my netstiff config file
+ test      html
+ htmlcmd   lynx -nolist -dump
+ client    netstiff
+ lang      de_DE
+ timeout   6

# local usage statistics
http://localhost/stats.php
  + start   /Statistics/
  + end     /Generating page took/

# sbeyer's homepage
http://pkqs.net/~sbeyer/

# buggy scripts test
http://localhost/buggyscripts/test.cgi
  + test /Internal Server Error/

# muetze's funny videos
ftp://foo:duff23@muetze.localnet/funnyvideos/
  + passive false
.fi

.SH "TEST METHODS"
.LP
The following test methods can be used:
.TP
\fBdate\fP
On HTTP URIs,
this method downloads the HTTP header to check when the file
has last been modified.
To make this feature work, the server should response
the \fILast-Modified\fP header entity.
This behaviour can become useless when fetching some dynamic web sites.
.br
On FTP URIs,
this method requests the last modification date of the file
on the FTP site to check when the file has last been modified.
.TP
\fBdiff\fP
This method downloads the 
HTTP content, FTP file or FTP directory listing 
and saves the two last versions.
Later you can use \fCnetstiff diff\fP to take a look at a 
diff of these versions.
.TP
\fBhtml\fP
This method acts like \fCdiff\fP,
but assumes to get HTML input
and preprocesses it to it more human-readable.
.br
See also the description of the \fChtmlcmd\fP option
in section \fBCONFIGURATION FILE / CONFIGURATION OPTIONS\fP.
.br
This method is not available on FTP URIs.
.TP
\fBmd5sum\fP
This method downloads the HTTP header to check if the MD5 sum has changed.
The server should response the \fIContent-MD5\fP header entity to make this
method work.
.br
Use this method on big binary files on HTTP sites and only if
the server supports it. (\fCnetstiff\fP will tell you.)
.br
This method is not available on FTP URIs.
.TP
\fBsize\fP
On HTTP URIs, 
this method downloads the HTTP header to check if the file
size has changed.
This feature needs the server to response 
the \fIContent-Length\fP header entity.
.br
On FTP URIs,
this method requests the size of the file on the FTP site
to check if it has changed.
.TP
\fB/regexp/\fP
This method downloads the HTTP content and checks if the 
given regular expression matches.
No data is stored locally.
.br
This method is not available on FTP URIs.

.SH "RETURN VALUE"
.LP
The number of errors are returned. So exit code 0 is success.

.SH "BUGS"
.LP
The regular expression stuff is using the \fIeval\fP function of
Ruby. This means that you are able to do non-regex-related stuff
using special strings as `regular expressions'. This is a big 
security issue when using netstiff as a backend for e.g. Web
applications. So do NOT do it and NEVER start netstiff on foreign,
unchecked configurations (\fB-W\fP can be dangerous). 

Feel free to send feedback, bug reports, etc.

.SH "AUTHOR AND COPYRIGHT"
.LP
\(co 2004, 2007-2008 Stephan Beyer \fC<s\-beyer@gmx.net>\fP, GNU GPL
