.TH "WEBDIFF" "1" "20040720" "sbeyer" "web"
.SH "NAME"
.LP
webdiff \- powerful and easy tool to check for web page updates
.SH "SYNOPSIS"
.LP
\fBwebdiff\fR [\fIoption\fP]
.SH "DESCRIPTION"
.LP
webdiff is a powerful web page update checker. You can choose between
different methods (diff, size, date, md5sum, regexp) webdiff should
check for. It will only print the URIs of web pages which changed,
so that its output can easily be used by further scripts (e.g. \fIwget\fP
or \fImail\fP).

webdiff exits after checking of all configured web pages. On connection
errors it just leaves a message in the log file (\fI~/.webdiff/lastlog\fP).
Use it with \fIcron\fP if you want to check for updates regularly.
.SH "OPTIONS"
.LP
You can only pass one argument. All further arguments to webdiff
are ignored.
.TP
\fB\-\-configure\fR, \fB\-c\fR
Use this option if you want to start the interactive configuration tool 
of webdiff. Of course, you may also edit the configuration file in 
\fI~/.webdiff/config\fP. I recommend the configuration tool
if you are new to webdiff, because it explains the possible test methods,
checks your regexp, etc.
.br
If the config file doesn't exit, the configuration tool is started 
automatically.
.TP
\fB\-\-diff\fR, \fB\-d\fR
Use this option if you want to get a \fIdiff(1)\fP between the last two
versions of the web pages using test method `diff'. See \fBBUGS\fR.
.TP
\fB\-\-help\fR, \fB\-h\fR
Use this option to get usage information about webdiff.
.TP
\fB\-\-version\fR, \fB\-v\fR
This option will display version number and copyright.
.SH "RESTRICTIONS"
4xx HTTP error code are handled like usual web pages. There won't be
a message, please check on your own.
.SH "BUGS"
The \fB\-\-diff\fR output format is not equal to the unified format of
\fIdiff(1)\fP, but it is related.
.SH "AUTHOR AND COPYRIGHT"
\(co Stephan Beyer <s\-beyer@gmx.net>, 2004, GPL
