.TH "WEBDIFF" "1" "20070227" "sbeyer" "web"
.SH "NAME"
.LP
webdiff \- powerful and easy tool to check for web page updates
.SH "SYNOPSIS"
.LP
\fBwebdiff\fR [\fIoption\fP]
.SH "DESCRIPTION"
.LP
Webdiff is a powerful and easy-to-use tool which checks for web page
updates. Updates are recognized using several test criteria (\fCdiff\fR,
\fChtml\fR, \fCsize\fR, \fCdate\fR, \fCmd5sum\fR, \fCregexp\fR). Please
see the configurator for more information on these methods.

Without any given options, webdiff will only check for updates 
of the specified URIs and only print those that changed, one per
line, so that the output of webdiff can easily be used by 
further scripts (e.g. \fIwget\fP or \fImail\fP).
If no configuration file exists, the configurator is launched
instead.

Webdiff exits after all configured web pages are checked. Occuring 
warnings and errors leave a message in the log file 
(\fI~/.webdiff/lastlog\fP) and are not written to stderr.
The exit code will be the number of errors that occured. So exit
code 0 is success.

Use it with \fIcron\fP if you want to check for updates regularly.

.SH "OPTIONS"
.LP
You can only pass one argument. All further arguments to webdiff
are ignored.
.TP
\fB\-\-configure\fR, \fB\-c\fR
Use this option if you want to start the configurator, the interactive
configuration tool of webdiff. Of course, you may also edit the 
configuration file in \fI~/.webdiff/config\fP by hand. Using the 
configurator is recommended if you are a new webdiff user, because
it explains the possible test methods, validates your regexps, etc.
Nevertheless, the configuration file format is very easy.
.br
The configurator will not initialize the webdiff cache for added
URIs, meaning: it will not download anything. To do so, you have to
rerun webdiff. This is a feature.
.br
If the config file does not exit, the configuration tool is started 
automatically.
.TP
\fB\-\-diff\fR, \fB\-d\fR
Use this option if you want to get a \fIdiff(1)\fP between the last two
versions of the web pages that are configured with test method \fCdiff\fR
or \fChtml\fR. See \fBBUGS\fR.
.TP
\fB\-\-help\fR, \fB\-h\fR
Use this option to get usage information about webdiff. To be honest,
this manual page in conjunction with the configurator is a better 
documentation.
.TP
\fB\-\-reset\fR, \fB\-r\fR
Use this option after you noticed all differences with the \fB\-d\fR 
option, so that \fB\-d\fR will not show you the same changes again and
again.
.TP
\fB\-\-version\fR, \fB\-v\fR
This option will display version number and copyright.

.SH "RESTRICTIONS"
.LP
There is no special case to handle status codes other than 200. In 
practice, webdiff will neither follow redirections nor will it notice
any 4xx or 5xx error code. The resulting error pages are treated like
usual web pages. No logged message. Please check on your own.

.SH "USAGE EXAMPLE"
.LP
You want to add a new URI webdiff should check for updates.
.nf
\&        \fCwebdiff \-c\fR
.fi
The configurator is not described here. I know some weaknesses in
usability, but you can get along with it. When you are seeing your 
shell prompt again, you know that webdiff should retrieve an initial 
version of the web page you specified.
.nf
\&        \fCwebdiff\fR
.fi
After some weeks in the sun you want to see if something has changed. 
So you let webdiff check for updates.
.nf
\&        \fCwebdiff\fR
.fi
It is printing an URI! Let's see the changes!
.nf
\&        \fCwebdiff \-d\fR
.fi
Oh, it is so much, that it does not fit on a screen!
.nf
\&        \fCwebdiff \-d | pager\fR
.fi
Now you are satisfied because you read all the changes. So you finally
do
.nf
\&        \fCwebdiff \-r\fR
.fi
and webdiff forgets about the changes.

.SH "BUGS"
.LP
The \fB\-\-diff\fR output format is not equal to the unified format of
\fIdiff(1)\fP, but it is related.

The regular expression stuff is using the \fIeval\fP function of
Ruby. This means that you are able to do non\-regex\-related stuff
using special strings as `regular expressions'. This is a big 
security issue when using webdiff as a backend for e.g. web
applications.

.SH "THANKS TO"
.LP
I have to thank the following people for contributing to webdiff:
Alexander Logvinov (for a lot of testing, bugfinding and
feature ideas), Roland Krystian Alberciak (some discussion) and
Martin Aumueller (made me using webdiff again).

.SH "AUTHOR AND COPYRIGHT"
.LP
\(co Stephan Beyer \fC<s\-beyer@gmx.net>\fR, 2004, 2007, GNU GPL
